name: Docker Build and Run

on:
  push:
    branches:
      - master

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        
    - name: Checkout Frontend Repository
      uses: actions/checkout@v3
      with:
        path: Frontend-app

    - name: Build Frontend Docker Image
      with:
        path: Frontend-app
        run: docker build -t meu-front-end .

    - name: Run Frontend Docker Container
      with:
        path: Frontend-app
        run: docker run -d -p 3000:3000 meu-front-end

    - name: Run Frontend Docker Swarm
      with:
        path: Frontend-app
        run: docker swarm init

    - name: Create Frontend Docker Swarm Service
      with:
        path: Frontend-app
        run: docker service create --name meu-front-end --replicas 3 -p 3000:3000 meu-front-end

  build-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        
    - name: Checkout Backend Repository
      uses: actions/checkout@v3
      with:
        path: Backend-app

    - name: Build Backend Docker Image
      with:
        path: Backend-app
        run: docker build -t meu-backend .

    - name: Run Backend Docker Container
      with:
        path: Backend-app
        run: docker run -d -p 3030:3030 meu-backend

    - name: Run Backend Docker Swarm
      with:
        path: Backend-app
        run: docker swarm init

    - name: Create Backend Docker Swarm Service
      with:
        path: Backend-app
        run: docker service create --name meu-backend --replicas 3 -p 3030:3030 meu-backend
